apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-secret
type: Opaque
data:
  # Les valeurs doivent être encodées en base64
  root-password: cm9vdA==  # 'root' encodé en base64

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-db-config
data:
  MYSQL_ROOT_HOST: '%'
  MYSQL_DATABASE: 'djangodb'
  my.cnf: |
    [mysqld]
    lower_case_table_names=1