apiVersion: apps/v1
kind: Deployment
metadata:
  name: kapend-app
spec:
  replicas: 1  # Valeur par défaut, ajustée par la commande de mise à l'échelle
  selector:
    matchLabels:
      app: kapend-app
  template:
    metadata:
      labels:
        app: kapend-app
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.28
        command:
        - sh
        - -c
        - >
          until nslookup mysqlserver; do
            echo 'Waiting for MySQL to be ready';
            sleep 2;
          done
      containers:
      - name: kapend-app
        image: stark275/kapend:v2
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: kapend-app-service
spec:
  selector:
    app: kapend-app
  type: NodePort
  ports:
  - port: 80  # Port externe exposé par le service
    targetPort: 8000  # Port sur les pods vers lequel le trafic est acheminé
    nodePort: 32043
