# Generated by Django 4.2.11 on 2024-05-16 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gescli', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='pays',
        ),
    ]
