# Generated by Django 4.2.11 on 2024-05-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gescli', '0002_remove_clients_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='pays',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
