# Generated by Django 4.2.11 on 2024-05-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gescli', '0003_clients_pays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='pays',
        ),
        migrations.AddField(
            model_name='clients',
            name='age',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clients',
            name='sexe',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
