version: "3.8"
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tpk8s

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - l1_ig_celery

    ########################### Redis ############################
  rediserver:
    container_name: redisserver_l1_ig
    image: redis
    restart: always
    ports:
      - 6379:6379 
    entrypoint: redis-server --appendonly yes
    networks:
      - l1_ig_celery

networks:
  l1_ig_celery:
volumes:
  rabbitmq-data:

########################### Celery Worker ############################
  # celery:
  #   image: # Dockerfile à ecrire
  #   restart: always
  #   command: celery -A ErpProject worker -l info  
  #   networks:
  #       - l1_ig_celery     
