# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Configuration globale pour tous les noeuds
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096 # la mémoire pour chaque VM
    vb.cpus = 4 # Allouer 4 CPUs pour chaque VM
  end

  (1..2).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.box = "ubuntu/focal64"
      node.vm.hostname = "node#{i}-microk8s"
      node.vm.network "public_network", bridge: "wlp0s20f3", ip: "192.168.113.10#{1+i}"
      # Configuration supplémentaire
      node.vm.provision "shell", inline: <<-SHELL
        sudo snap install microk8s --classic
        sudo microk8s status --wait-ready
        # Activation des addons nécessaires
        sudo microk8s enable dns storage
        # Ajout de l'utilisateur vagrant au groupe microk8s pour éviter les problèmes de permissions
        sudo usermod -a -G microk8s vagrant
        # S'ssurer que les changements prennent effet sans redémarrer
        newgrp microk8s
      SHELL
    end
  end
end

