apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kapend-app-cd
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  source:
    path: code/docker/4-kapend/myfirst/k8s
    repoURL: https://github.com/stark275/parallel-programming.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
